### ISSUE TITLE
[🚀 CDK Booster] Error: The service was stopped

### ISSUE THREAD

**Issue by DanielMarquesz** [ServerlessLife/cdk-booster#5]
## Description: 

Hi! I'm currently implementing the CDK Booster in some of my company's projects.

Some of our projects have more than 100 Lambdas, and CDK Booster cut the deploy time in half (from 6 minutes to 3 minutes).
But we have a bigger project with more than 200 Lambdas, and usually its deploy time goes up to >15 minutes. So I tried to use the booster, but got an error:

<img width="663" height="128" alt="Image" src="https://github.com/user-attachments/assets/0d07a65b-1510-40e4-ad95-b2894c691a42" />

From what I found, it looks like esbuild cannot handle the amount of new processes needed to build the Lambdas in parallel, so it starts closing some processes before finishing.

### Dependencies:

```json{
  "devDependencies": {
    "@commitlint/cli": "^18.4.2",
    "@commitlint/config-conventional": "^18.4.2",
    "@jest/types": "^30.0.5",
    "@side/jest-runtime": "^1.1.0",
    "@swc/core": "^1.7.24",
    "@swc/helpers": "^0.5.17",
    "@swc/jest": "^0.2.39",
    "@types/jest": "^30.0.0",
    "@types/node": "^24.3.0",
    "@typescript-eslint/eslint-plugin": "^6.7.2",
    "@typescript-eslint/parser": "^6.7.2",
    "commitizen": "^4.3.1",
    "esbuild": "^0.25.9",
    "eslint": "^8.49.0",
    "eslint-config-prettier": "^9.0.0",
    "eslint-config-standard": "^17.1.0",
    "eslint-plugin-import": "^2.23.4",
    "eslint-plugin-import-helpers": "^1.1.0",
    "eslint-plugin-node": "^11.1.0",
    "eslint-plugin-prettier": "^5.0.0",
    "eslint-plugin-promise": "^6.1.1",
    "jest": "^30.0.5",
    "jest-junit": "^16.0.0",
    "jest-sonar-reporter": "^2.0.0",
    "lefthook": "^1.5.2",
    "lint-staged": "^11.0.0",
    "prettier": "^3.0.3",
    "regenerator-runtime": "^0.14.1",
    "ts-node": "^10.9.1",
    "typescript": "^5.9.2"
  },
  "dependencies": {
    "@welbe/audit": "^1.0.2",
    "@welbe/core": "^0.0.57",
    "aws-cdk": "^2.1003.0",
    "aws-cdk-lib": "^2.182.0",
    "cdk-booster": "^1.0.1",
    "constructs": "^10.4.2",
    "reflect-metadata": "^0.1.13"
  }
}
`

**Comment by ServerlessLife** [comment]
Hi Daniel,

Thank you for reporting the issue. 

I will add a parameter to control the number of Lambdas bundled at once. I will add that shortly, at the latest over the weekend.

Marko

**Comment by ServerlessLife** [comment]
Hi Daniel,

I deployed alpha version `cdk-booster@1.1.0-alpha.1`, which has `batch` and `parallel` parameters.   `batch` sets the number of Lambdas bundled in a batch with ESBuild, `parallel` sets the number of parallel ESBuild processes.

You can start with something like this in `cdk.json`
```json
{
  "app": "npx cdk-booster bin/your_app.ts -v -b 20 -p 1" 
  ...
}
```

**Comment by DanielMarquesz** [comment]
Hi Marko,

Thanks for the answer. 
I've tried using your alpha version but apparently still not working. I pass the foollowing parameters: `npx cdk-booster bin/startup.ts -b 2 -p 1`.
Those are my logs:

```json

2025-09-25T13:46:45.7906011Z [🚀 CDK Booster] Welcome to CDK Booster 🚀 version 1.1.0-alpha.1.
2025-09-25T13:46:53.9255815Z [WARNING] aws-cdk-lib.aws_dynamodb.TableOptions#pointInTimeRecovery is deprecated.
2025-09-25T13:46:53.9256609Z   use `pointInTimeRecoverySpecification` instead
2025-09-25T13:46:53.9257339Z   This API will be removed in the next major release.
2025-09-25T13:47:03.6308253Z [🚀 CDK Booster] Bundling:
2025-09-25T13:47:03.6344603Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:03.6345274Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4617988Z [🚀 CDK Booster] Bundling:
2025-09-25T13:47:04.4627291Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4628186Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4629156Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4629639Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4630103Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4630531Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4630992Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4631502Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4631927Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4632355Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4632764Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4633168Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4633589Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4634040Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4634468Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4634867Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4635242Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4636171Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4636568Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4637001Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4644096Z [🚀 CDK Booster] Bundling:
2025-09-25T13:47:04.4645012Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4645494Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4645962Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4646435Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4646903Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4647326Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4647736Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4648132Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4648522Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4648934Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4649721Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4650150Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4650555Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4650937Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4651325Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4651740Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4652198Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4652637Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4653082Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4653514Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4653926Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4654327Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4654696Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4655069Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4655442Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4655826Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4656220Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4656601Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4657126Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4657501Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4657876Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4658288Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4658715Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4659127Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4659540Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4659930Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4660336Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4660751Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4661284Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4661683Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4662127Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4662557Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4663130Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4663572Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4663987Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4664422Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4664867Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4665297Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4665733Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4666170Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4666618Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4667082Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4667498Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4667871Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4668268Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4668673Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4669088Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4669469Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4669847Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4670377Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4670750Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4671169Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4671554Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4671954Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4672364Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4672770Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4673158Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4673562Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4673962Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4674371Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4674801Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4675221Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4675649Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4676228Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4676640Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4677059Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4677504Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4677935Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4678346Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4678754Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4679168Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4679576Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4679980Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4680407Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4680841Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4681244Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4681667Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4682106Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4682559Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4683011Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4683741Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4684153Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4684559Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4684947Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4685332Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4685740Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4686172Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4686605Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4687042Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4687483Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4687947Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4688432Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4689055Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4689475Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4689848Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4690249Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4690641Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4691013Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4691406Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4691836Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4692243Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4692618Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4693009Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4693416Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4693822Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4694224Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4694619Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4695000Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4695381Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4695769Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4696171Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4696725Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4697083Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4697461Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4697853Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4698292Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4698725Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4699160Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4699602Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4700004Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4700412Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4700833Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4701255Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4701674Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4702243Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4702644Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4703024Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4703403Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4703793Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4704156Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4704509Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4704856Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4705215Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4705597Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4705977Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4706362Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4706767Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4707177Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4707580Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4707968Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4708392Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4708834Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4709279Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4709898Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4710319Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4710708Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4711086Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4711444Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4711820Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4712191Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:47:04.4712563Z  - /azp/_work/r1/a/lambda-sample.ts
2025-09-25T13:51:01.6036380Z [🚀 CDK Booster] Error: The service was stopped
2025-09-25T13:51:01.6037074Z     at /azp/_work/r1/a/node_modules/esbuild/lib/main.js:949:34
2025-09-25T13:51:01.6037519Z     at responseCallbacks.<computed> (/azp/_work/r1/a/node_modules/esbuild/lib/main.js:603:9)
2025-09-25T13:51:01.6037908Z     at Socket.afterClose (/azp/_work/r1/a/node_modules/esbuild/lib/main.js:594:28)
2025-09-25T13:51:01.6038265Z     at Socket.emit (node:events:536:35)
2025-09-25T13:51:01.6038600Z     at endReadableNT (node:internal/streams/readable:1698:12)
2025-09-25T13:51:01.6038986Z     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

```

**Comment by ServerlessLife** [comment]
Thank you. This will help me a lot.

**Comment by ServerlessLife** [comment]
Hi Daniel,

Thank you for sending me logs via LinkedIn. 

I prepared a new alpha version cdk-booster@1.1.0-alpha.3

Looks like ESBuild just crashes for no apparent reason. It could be random, or there is something in one of the Lambda code that is causing issues.

I implemented four ways to resolve this: 
1. **Retrying.** 
You would see in the logs `Retrying bundling.` followed by  `Retry successful.` or `Retry failed.`. Let me know if this helps.
2. **If it fails, just skip the whole batch.**
CDK will still bundle them, but you will not take advantage of CDK Booster for those functions. It makes sense to limit the batch to a certain number; otherwise, too many functions would not be pre-bundled. 
3. **Skip functions that fail to bundle**
If you figure out which functions are problematic (by maybe setting batch parameter to 1), you can exclude them with the `SKIP_CDK_BOOSTER: true' environment variable. Note that it is an environmental variable on the `bundling` property, not a function. CDK will still bundle them.

```typescript
new lambda_nodejs.NodejsFunction(
  this,
  'Test',
  {
    entry: 'lambda.js',
    environment: {
      SOME_VAR: 'TEST',
    },
    bundling: {
      environment: {
        SKIP_CDK_BOOSTER: 'true',
      }
    },
  },
);
```

**Comment by DanielMarquesz** [comment]
Hi Marko,

I send to you more logs in the Linkedin but looks like the deploy is not stopped even if the lambda bundle fails. But now i'm receiving an error related to the entry file path:

<img width="969" height="17" alt="Image" src="https://github.com/user-attachments/assets/30cc3721-bfa1-4cdd-8a18-af8954befbde" />

We use  custom class extended from the `NodejsFunction`. And we customize it to ours folder patters. 

Ex1:

```
 const fn = new NodeFunction(this, name, {
      functionName: `${this.variables.serviceName}-${name}`,
      description,
      entry: path.join(__dirname, `/../../src/cron/${entry}.ts`),
    })
```

Ex2: 


```   
const fn = new NodeFunction(this, name, {
      functionName: `${this.variables.serviceName}-${name}`,
      description,
      entry: path.join(__dirname, `/../../src/lambdas/${entry}.ts`),
    })```
